<?php
  /**
  * Text Block
  *
  * This block was generated by create-acf-block-json.
  *
  * @package WordPress
  *
  * @param   array $block The block settings and attributes.
  * @param   string $content The block inner HTML (empty).
  * @param   bool $is_preview True during AJAX preview.
  * @param   (int|string) $post_id The post ID this block is saved to.
  */

  $allowed_blocks = array( 'core/paragraph', 'core/heading', 'core/list' );

  $template = array(
    array('core/paragraph', array(
      'content' => 'Type here... ',
    ))
  );
  $block_meta = ehd_get_block_meta( $block, $is_preview );

?>

<div <?php echo $block_meta; ?>>
  <div class="container">

    <?php
		  echo '<InnerBlocks allowedBlocks="' . esc_attr( wp_json_encode( $allowed_blocks ) ) . '" template="' . esc_attr( wp_json_encode( $template ) ) . '" />';
	?>
  </div>
</div>