<?php
/**
* Video Block
*
* This block was generated by create-acf-block-json.
*  
* @package WordPress
*
* @param   array $block The block settings and attributes.
* @param   string $content The block inner HTML (empty).
* @param   bool $is_preview True during AJAX preview.
* @param   (int|string) $post_id The post ID this block is saved to.
*/

  $block_meta = ehd_get_block_meta( $block, $is_preview );

  $video_url = get_field('video_url');
  $video_image = get_field('video_image');
  $image = false;
  if($video_image){
    $image = $video_image;
  }

  $args = array(
    'video_url' => $video_url,
    'video_image' => $image
  );
?>
<?php if($video_url){ ?>
  <div <?php echo $block_meta; ?>>
    <?php get_template_part('blocks/video/video', '', $args); ?>
  </div>
<?php } ?>