<?php
/**
* Page Header Block
*
* This block was generated by create-acf-block-json.
*  
* @package WordPress
*
* @param   array $block The block settings and attributes.
* @param   string $content The block inner HTML (empty).
* @param   bool $is_preview True during AJAX preview.
* @param   (int|string) $post_id The post ID this block is saved to.
*/

  $block_meta = ehd_get_block_meta( $block, $is_preview );

  $page_title = get_field('page_title');
  $page_heading = get_field('page_title') ? get_the_title() : get_field('page_heading');
  $text = get_field('text');
  $background_image = get_field('background_image');

?>

<div <?php echo $block_meta; ?>>
  <div class="page-header-inner ehd-grid">
    <div class="page-header-inner-meta">
      <h1><?php echo $page_heading; ?></h1>
      <?php if ($text) { ?>
        <div class="page-header-inner-text">
          <?php echo $text; ?>
        </div>
      <?php } ?>
    </div>
    <?php if ($background_image) { ?>
      <div class="page-header-inner-image">
        <?php echo wp_get_attachment_image($background_image['id'], 'full', false, array(
          'loading' => 'lazy',
          'class' => 'aligncenter',
        )); ?>
      </div>
    <?php } ?>
  </div>
</div>