<?php
/**
* Image Carousel Block
*
* This block was generated by create-acf-block-json.
*  
* @package WordPress
*
* @param   array $block The block settings and attributes.
* @param   string $content The block inner HTML (empty).
* @param   bool $is_preview True during AJAX preview.
* @param   (int|string) $post_id The post ID this block is saved to.
*/

  $block_meta = ehd_get_block_meta( $block, $is_preview );

  $images = get_field('carousel_images');

  $args = array(
    'images' =>$images,
  );

?>

<div <?php echo $block_meta; ?>>
  <?php if($images){ ?>
    <div class="block-image-carousel-wrapper">
      <?php get_template_part('blocks/image-carousel/image-carousel', '', $args); ?>
    </div>
  <?php } ?>
</div>