<?php
/**
* People Block
*
* This block was generated by create-acf-block-json.
*  
* @package WordPress
*
* @param   array $block The block settings and attributes.
* @param   string $content The block inner HTML (empty).
* @param   bool $is_preview True during AJAX preview.
* @param   (int|string) $post_id The post ID this block is saved to.
*/

  $block_meta = ehd_get_block_meta( $block, $is_preview );
  $people_ids = get_field('people');
  $headshot_visibility = get_field('headshot_visibility');
  if($people_ids){
    $argsPeople = array(
      'post_type' => 'person',
      'posts_per_page' => -1,
      'post__in'=> $people_ids,
      'orderby' => 'post__in'
    );
    $queryPeople = new WP_Query( $argsPeople );
?>

<div <?php echo $block_meta; ?>>
  <?php if($queryPeople->have_posts()) { ?>
    <div class="people-row">
       <?php 
        while($queryPeople->have_posts()) { 
          $queryPeople->the_post();
          $post_id = get_the_ID();
          $imageID = get_post_thumbnail_id($post_id);
          $name = get_the_title($post_id);
          $role = get_field('role', $post_id);
          $personID = $post_id;
          $modelID = $rowIndex.'_'.$personID;
          $content = get_field('bio', $post_id);
          $all_fields = get_fields($post_id);
        ?>
         <div class="person-preview">
          <a <?php if(!empty($content)) { ?>data-fancybox="person" data-src="#modal-featured-<?php echo $modelID; ?>" data-slug="<?php echo urlencode($name); ?>" href="javascript:;" <?php } ?>>
          
            <?php 
              if($headshot_visibility != 'hide-headshots') { ?>
                <div class="person-preview-image star-container">
                  <?php echo wp_get_attachment_image($imageID, 'feature-square', false, array(
                    'class' => 'aligncenter starflash',
                    'alt' => $name
                  )); ?>
                  <img src="<?php bloginfo('template_url'); ?>/dist/images/sparkle.png" alt="sparkle" class="sparkle">
                  
              </div>
            <?php } // end hide-headshots check ?>
          
          <div class="person-preview-meta">
            <h4 class="name underline-red"><?php echo $name; ?></h4>
            <p  class="role"><?php echo $role; ?></p>
          </div>
        </a>
        <?php if(!empty($content)) { ?>
            <div class="people-modal" id="modal-featured-<?php echo $modelID; ?>">
              <h4 class="name"><?php echo $name; ?></h4>
              <p  class="role"><span class="underline-red"><?php echo $role; ?></span></p>
              <div>
                <?php 
                  if($headshot_visibility != 'hide-headshots') {
                    echo wp_get_attachment_image($imageID, 'feature-square', false, array(
                    'class' => 'alignright',
                    'alt' => $name
                  ));
                  } // end hide-headshots check
                ?>
                <div class="bio">
                  <?php echo apply_filters( 'the_content', $content ); ?>
                </div>
            </div>
          </div>
          <?php } ?>
        </div>

        <?php } ?>
    </div>
  <?php } ?>

</div>
<?php } elseif($is_preview) { ?>
  <div <?php echo $block_meta; ?>>
    <h2>Please select people to show in the sidebar options</h2>
  </div>
<?php  } ?>