<?php

/**
 * logos Block
 *
 * This block was generated by create-acf-block-json.
 *  
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 */

$block_meta = ehd_get_block_meta($block, $is_preview);

$logos = get_field('logos');
$include_border = get_field('include_border');
$logo_item_class = $include_border ? 'logo-item include-border' : 'logo-item';


?>

<div <?php echo $block_meta; ?>>
 <div class="logos-grid">
  <?php foreach ($logos as $logo) : ?>
    <div class="<?php echo esc_attr($logo_item_class); ?>">
      <?php if ($logo['link']) : ?>
        <a href="<?php echo esc_url($logo['link']); ?>" target="_blank" rel="noopener noreferrer">
          <img src="<?php echo esc_url($logo['image']['url']); ?>" alt="<?php echo esc_attr($logo['image']['alt']); ?>" />
        </a>
      <?php else : ?>
        <img src="<?php echo esc_url($logo['image']['url']); ?>" alt="<?php echo esc_attr($logo['image']['alt']); ?>" />
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
  </div>
</div>