<?php
  /**
  * Text Block
  *
  * This block was generated by create-acf-block-json.
  *
  * @package WordPress
  *
  * @param   array $block The block settings and attributes.
  * @param   string $content The block inner HTML (empty).
  * @param   bool $is_preview True during AJAX preview.
  * @param   (int|string) $post_id The post ID this block is saved to.
  */

  // showme($attributes);

  if ($attributes['tabLabel']) {
    $tabLabel = $attributes['tabLabel'];
    $tabID = sanitize_title($tabLabel);
  }
  
  $isTabComponent = $attributes['parentBlock'] == 'ehd/tabs' ? true : false;
  
  if($isTabComponent){
?>
  <article aria-labelledby="<?php echo 'tab-'.$tabID; ?>" id="<?php echo esc_attr($tabID); ?>" class="block-tab">
    <div class="inner-tab" tabindex='1'>
      <?php echo $content; ?>
    </div>
  </article>
<?php } else { ?>
  <section>
    <h2>
      <button
        type="button"
        aria-expanded="false"
        aria-controls="accordion-item-<?php echo esc_attr($tabID); ?>-content"
      >
        <?php echo $tabLabel; ?>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 256 256"
          aria-hidden="true"
          focusable="false"
        >
          <polygon points="0,64 128,192 256,64" />
        </svg>
      </button>
    </h2>
    <div id="accordion-item-<?php echo esc_attr($tabID); ?>-content" class="accoridion-item-content">
      <div class="accoridion-item-content-inner">
        <?php echo $content; ?>
      </div>
    </div>
  </section>
<?php } ?>