<?php
  /**
  * buttons Block
  *
  * This block was generated by create-acf-block-json.
  *  
  * @package WordPress
  *
  * @param   array $block The block settings and attributes.
  * @param   string $content The block inner HTML (empty).
  * @param   bool $is_preview True during AJAX preview.
  * @param   (int|string) $post_id The post ID this block is saved to.
  */

  $block_meta = ehd_get_block_meta( $block, $is_preview );

  $buttons = get_field('buttons');
  $vertical_alignment = get_field('vertical_alignment');
  $vertical_alignment_mobile = get_field('vertical_alignment_mobile');
  $horizontal_alignment = get_field('horizontal_alignment');
?>

<div <?php echo $block_meta; ?>>
    <div class="button-wrap <?php echo $vertical_alignment.' '.$horizontal_alignment.' '.$vertical_alignment_mobile; ?>">
	    <?php
      if($buttons){
        foreach($buttons as $button){
            $url = $button['button_link']['url'];
            $title = $button['button_link']['title'];
            $target = $button['button_link']['target'];
            $button_type = $button['button_type'];
          ?>
          <a href="<?php echo $url; ?>" class="button <?php echo $button_type; ?>" target="<?php echo $target; ?>">
            <?php echo $title; ?>
          </a>
        <?php } ?>
      <?php } ?>
  </div>
</div>