<?php
  /**
  * Text Block
  *
  * This block was generated by create-acf-block-json.
  *
  * @package WordPress
  *
  * @param   array $block The block settings and attributes.
  * @param   string $content The block inner HTML (empty).
  * @param   bool $is_preview True during AJAX preview.
  * @param   (int|string) $post_id The post ID this block is saved to.
  */

  $className = "";

  $wrapper_attributes = get_block_wrapper_attributes(
    [
      'class' => $className
    ]
  );
?>
  <div <?php echo $wrapper_attributes; ?>>
    <div class="accordion-inner">
      <?php echo $content; ?>
    </div>
  </div>
