<?php
/**
* Video Text Block
*
* This block was generated by create-acf-block-json.
*  
* @package WordPress
*
* @param   array $block The block settings and attributes.
* @param   string $content The block inner HTML (empty).
* @param   bool $is_preview True during AJAX preview.
* @param   (int|string) $post_id The post ID this block is saved to.
*/

  $block_meta = ehd_get_block_meta( $block, $is_preview );
  
  $args = get_fields();
  
  $video_url = $args['video_url'];
  
  $video_placeholder_image = isset($args["video_image"]) ?  $args["video_image"] : false;
  
  $video_side = $args['video_side'];





  $template = array(
    array('core/heading', array(
      'level' => 3,  // Specifies that the heading should be an H1
      'placeholder' => 'Add your title',
    )),
    array('core/paragraph', array(
      'placeholder' => 'Add your content here',
    )),
    array('ehd/button', array(
        'name' => 'ehd/button',
        'data' => array(
            'block_ehd_button_buttons' => array(
                '661f7d53b46a4' => array(
                    'block_ehd_button_button_link' => array(
                        'title' => 'My Button',
                        'url' => '#',
                        'target' => ''
                    ),
                    'block_ehd_button_button_type' => 'button-primary'
                )
            ),
            'block_ehd_button_vertical_alignment' => 'flex-left',
            'block_ehd_button_vertical_alignment_mobile' => 'flex-stretch-mob',
            'block_ehd_button_horizontal_alignment' => 'flex-row',
        ),
        'mode' => 'preview'
    ))
  );

?>

<div <?php echo $block_meta; ?>>
  <div class="container <?php echo $video_side; ?>">
    <div class="video-text-text">
        <?php echo '<InnerBlocks template="' . esc_attr( wp_json_encode( $template ) ) . '" />'; ?>
    </div>
    <div class="video-text-video">
      <?php if($video_url){ ?>
        <?php get_template_part('blocks/video/video', 'single', [
          'video_url' => $video_url,
          'video_image' => $video_placeholder_image,
        ]); ?>
      <?php } ?>
  </div>
</div>