<?php
  /**
  * Image Gallery Block
  *
  * This block was generated by create-acf-block-json.
  *  
  * @package WordPress
  *
  * @param   array $block The block settings and attributes.
  * @param   string $content The block inner HTML (empty).
  * @param   bool $is_preview True during AJAX preview.
  * @param   (int|string) $post_id The post ID this block is saved to.
  */
  $gallery = get_field('gallery');

  $block_meta = ehd_get_block_meta( $block, $is_preview );

?>

<div <?php echo $block_meta; ?>>

	  <?php if($gallery){?>
    
      <div class='image-gallery'>
    
        <?php foreach($gallery as $image){  ?>
          <a href="<?php echo $image['sizes']['large']; ?>" data-fancybox="gallery" data-caption="<?php echo $image['title']; ?>">
            <?php echo wp_get_attachment_image($image['id'], 'feature-square', false, array(
              'loading' => 'lazy',
            )); ?>
          </a>
        <?php } // end foreach $gallery?>
    
      </div>
    <?php } // end foreach $gallery ?>
</div>