<?php
			if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_53c8a7d12c35a',
	'title' => 'Media',
	'fields' => array(
		array(
			'key' => 'field_54b6f67d92240',
			'label' => 'Pre Password Text',
			'name' => 'pre_password_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_53c8a7d96c0bd',
			'label' => 'Files',
			'name' => 'files',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add File',
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_53c8a7e46c0be',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_53c8a7ec6c0bf',
					'label' => 'Url',
					'name' => 'url',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					'key' => 'field_624a36323c64a',
					'label' => 'Downloadable File',
					'name' => 'downloadable_file',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
        array(
          'key' => 'field_64701096ed85f',
          'label' => 'Live Time',
          'name' => 'live_time',
          'aria-label' => '',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'd/m/Y g:i a',
          'return_format' => 'Y-m-d H:i:s',
          'first_day' => 1,
        ),
      ),
		),
    array(
      'key' => $key.'media_images',
      'label' => 'Images',
      'name' => 'media_images',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add item',
      'sub_fields' => array(
        array(
          'key' => $key.'image',
          'label' => 'Image',
          'name' => 'image',
          'type' => 'image',
          'parent' => '',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'default_value' => '',
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => 0,
          'min_height' => 0,
          'min_size' => 0,
          'max_width' => 0,
          'max_height' => 0,
          'max_size' => 0,
          'mime_types' => '',
        ),
        array(
          'key' => $key.'high_res',
          'label' => 'High Res download link',
          'name' => 'high_res',
          'type' => 'url',
          'parent' => '',
          'instructions' => 'Optional, if you want to host large files elsewhere, you can put the link here.',
          'required' => 0,
          'conditional_logic' => 0,
          'default_value' => '',
          'placeholder' => '',
        ),
        array(
          'key' => $key.'description',
          'label' => 'Description',
          'name' => 'description',
          'type' => 'text',
          'parent' => '',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array(
          'key' => $key.'photo_credit',
          'label' => 'Photo Credit',
          'name' => 'photo_credit',
          'type' => 'text',
          'parent' => '',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array(
          'key' => $key.'field_64701096ed85f',
          'label' => 'Live Time',
          'name' => 'live_time',
          'aria-label' => '',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'd/m/Y g:i a',
          'return_format' => 'Y-m-d H:i:s',
          'first_day' => 1,
        ),
      ),
    ),
		array(
			'key' => 'field_53c8a8136c0c0',
			'label' => 'Video',
			'name' => 'video',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Video',
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_53c8a82a6c0c1',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_53c8a8356c0c2',
					'label' => 'YouTube Link',
					'name' => 'youtube_link',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
				array(
					'key' => 'field_53c8a83e6c0c3',
					'label' => 'Download Link',
					'name' => 'download_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5dc69fb49cf2e',
					'label' => 'Thumbnail',
					'name' => 'thumbnail',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
        array(
          'key' => 'field_64701096ed8s5f',
          'label' => 'Live Time',
          'name' => 'live_time',
          'aria-label' => '',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'd/m/Y g:i a',
          'return_format' => 'Y-m-d H:i:s',
          'first_day' => 1,
        ),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '38',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
    1 => 'block_editor'
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		